### ISSUE TITLE
Add Option

### ISSUE THREAD

**Issue by sylv256** [naritanara/vanity-splash-text#3]
Add an option to toggle this mod's function.

**Comment by naritanara** [comment]
This doesn't make much sense if you can just remove the mod from your game. Thanks for the suggestion, though.

**Comment by sylv256** [comment]
(modpacks)

**Comment by naritanara** [comment]
I see your point, but modpacks can still be modified to leave out mods that you don't want.  Also, due to the planned migration to lib39, this may become a technical challenge due to how the library manages splash texts. I will look into it, but this may need a PR to lib39 to implement the necesary infrastructure.
